sample_quotes = [
    {"text": "I am so clever that sometimes I don't understand a single word of what I am saying.", "author": "Oscar Wilde"},
    {"text": "I'm not lazy, I'm on energy-saving mode.", "author": "A Spirit Animal"},
    {"text": "Go to heaven for the climate, hell for the company.", "author": "Mark Twain"},
    {"text": "My bed is a magical place where I suddenly remember everything I forgot to do.", "author": "The Procrastinator's Creed"},
    {"text": "I'm not great at the advice. Can I interest you in a sarcastic comment?", "author": "Chandler Bing"},
    {"text": "Some people are like clouds. When they disappear, it's a beautiful day.", "author": "A Frustrated Observer"},
    {"text": "Light travels faster than sound. This is why some people appear bright until you hear them speak.", "author": "Alan Dundes"},
    {"text": "My life is about as organized as the $5 DVD bin at a gas station.", "author": "A Millennial's Diary"},
    {"text": "The cure for boredom is curiosity. There is no cure for curiosity.", "author": "Dorothy Parker"},
    {"text": "If you want to look thin and young, hang around with old, fat people.", "author": "Jim Eason"},
    {"text": "I always wanted to be somebody, but now I realize I should have been more specific.", "author": "Lily Tomlin"},
    {"text": "Common sense is like deodorant. The people who need it most never use it.", "author": "A Public Service Announcement"},
    {"text": "Never half-ass two things. Whole-ass one thing.", "author": "Ron Swanson"},
    {"text": "If at first you don't succeed, then skydiving is probably not for you.", "author": "Steven Wright"},
    {"text": "I like work; it fascinates me. I can sit and look at it for hours.", "author": "Jerome K. Jerome"},
    {"text": "Due tomorrow? Do tomorrow.", "author": "A Student's Mantra"},
    {"text": "The only thing that ever sat its way to success was a hen.", "author": "Sarah Brown"},
    {"text": "I am not a member of any organized political party. I am a Democrat.", "author": "Will Rogers"},
    {"text": "Life is short. Smile while you still have teeth.", "author": "A Pragmatic Dentist"},
    {"text": "I'm not arguing, I'm just explaining why I'm right.", "author": "Every Sibling Ever"},
    {"text": "The reason I talk to myself is because I’m the only one whose answers I accept.", "author": "George Carlin"},
    {"text": "I haven't spoken to my wife in years. I didn't want to interrupt her.", "author": "Rodney Dangerfield"},
    {"text": "That's what I do: I drink and I know things.", "author": "Tyrion Lannister"},
    {"text": "I would like to be the ideal mother, but I'm too busy raising my kids.", "author": "An Honest Parent"},
    {"text": "My opinions may have changed, but not the fact that I am right.", "author": "Ashleigh Brilliant"},
    {"text": "Zombies eat brains. You're safe.", "author": "A Backhanded Compliment"},
    {"text": "I used to be a people person, but people ruined that for me.", "author": "A Retired Extrovert"},
    {"text": "If you think nobody cares if you’re alive, try missing a couple of car payments.", "author": "Earl Wilson"},
    {"text": "The first thing I do in the morning is brush my teeth and sharpen my tongue.", "author": "Dorothy Parker"},
    {"text": "I am not anti-social. I am selectively social. There is a difference.", "author": "An Introvert's Manifesto"},
    {"text": "If I agreed with you we'd both be wrong.", "author": "Winston Churchill"},
    {"text": "My favorite machine at the gym is the vending machine.", "author": "A Fitness Enthusiast"},
    {"text": "Why is there so much month left at the end of my money?", "author": "Your Bank Account"},
    {"text": "The only mystery in life is why the kamikaze pilots wore helmets.", "author": "Al McGuire"},
    {"text": "I'm not a complete idiot, some parts are missing.", "author": "A Humble Genius"},
    {"text": "I believe we should all pay our tax with a smile. I tried, but they wanted cash.", "author": "A Reluctant Taxpayer"},
    {"text": "I am an early bird and a night owl. So I am wise and I have worms.", "author": "Michael Scott"},
    {"text": "Life is a soup and I'm a fork.", "author": "An Existentialist"},
    {"text": "I'm on a seafood diet. I see food, and I eat it.", "author": "My Stomach"},
    {"text": "Of course I talk to myself. Sometimes I need expert advice.", "author": "My Ego"},
    {"text": "If you're going to tell people the truth, be funny or they'll kill you.", "author": "Billy Wilder"},
    {"text": "I don't need anger management. I need people to stop pissing me off.", "author": "A Calm Individual"},
    {"text": "Everything is funny, as long as it's happening to somebody else.", "author": "Will Rogers"},
    {"text": "Sarcasm is the body's natural defense against stupidity.", "author": "The Internet"},
    {"text": "I'd agree with you but then we'd both be wrong.", "author": "A Diplomat"},
    {"text": "It's a basic truth of the human condition that everybody lies.", "author": "Dr. House"},
    {"text": "People say nothing is impossible, but I do nothing every day.", "author": "A.A. Milne"},
    {"text": "I am not saying I am Batman, I am just saying no one has ever seen me and Batman in a room together.", "author": "A Hopeful Vigilante"},
    {"text": "If toast always lands butter-side down, and cats always land on their feet, what happens if you strap toast on the back of a cat?", "author": "A Physicist's Nightmare"},
    {"text": "I'm not sure what's tighter: our jeans or our budget.", "author": "A Realist"},
    {"text": "Behenchod ma chuda", "author":"arse"},
    {"text":"Akal gand me rakha h kya jo roj subah hag ke nikal deta", "author": "some wise men"}
]
